# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/hl3g/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/hl3g/proprietary/bin/lpm:system/bin/lpm \
    vendor/samsung/hl3g/proprietary/bin/mcDriverDaemon:system/bin/mcDriverDaemon \
    vendor/samsung/hl3g/proprietary/bin/at_distributor:system/bin/at_distributor \
    vendor/samsung/hl3g/proprietary/bin/gps.cer:system/bin/gps.cer \
    vendor/samsung/hl3g/proprietary/bin/gpsd:system/bin/gpsd \
    vendor/samsung/hl3g/proprietary/bin/macloader:system/bin/macloader \
    vendor/samsung/hl3g/proprietary/bin/mcDriverDaemon:system/bin/mcDriverDaemon \
    vendor/samsung/hl3g/proprietary/bin/mfgloader:system/bin/mfgloader \
    vendor/samsung/hl3g/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/hl3g/proprietary/bin/smdexe:system/bin/smdexe \
    vendor/samsung/hl3g/proprietary/bin/wlandutservice:system/bin/wlandutservice \
    vendor/samsung/hl3g/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/samsung/hl3g/proprietary/etc/gps.xml:system/etc/gps.xml \
    vendor/samsung/hl3g/proprietary/etc/init.sec.boot.sh:system/etc/init.sec.boot.sh \
    vendor/samsung/hl3g/proprietary/etc/plmn_se13.bin:system/etc/plmn_se13.bin \
    vendor/samsung/hl3g/proprietary/etc/srm.bin:system/etc/srm.bin \
    vendor/samsung/hl3g/proprietary/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/hl3g/proprietary/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/hl3g/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/hl3g/proprietary/app/FFFFFFFF000000000000000000000001.drbin:system/app/FFFFFFFF000000000000000000000001.drbin \
    vendor/samsung/hl3g/proprietary/app/mcRegistry/00060308060501020000000000000000.tlbin:system/app/mcRegistry/00060308060501020000000000000000.tlbin \
    vendor/samsung/hl3g/proprietary/app/mcRegistry/02010000080300030000000000000000.tlbin:system/app/mcRegistry/02010000080300030000000000000000.tlbin \
    vendor/samsung/hl3g/proprietary/app/mcRegistry/07010000000000000000000000000000.tlbin:system/app/mcRegistry/07010000000000000000000000000000.tlbin \
    vendor/samsung/hl3g/proprietary/app/mcRegistry/07060000000000000000000000000000.tlbin:system/app/mcRegistry/07060000000000000000000000000000.tlbin \
    vendor/samsung/hl3g/proprietary/app/mcRegistry/ffffffff000000000000000000000003.tlbin:system/app/mcRegistry/ffffffff000000000000000000000003.tlbin \
    vendor/samsung/hl3g/proprietary/app/mcRegistry/ffffffff000000000000000000000004.tlbin:system/app/mcRegistry/ffffffff000000000000000000000004.tlbin \
    vendor/samsung/hl3g/proprietary/app/mcRegistry/ffffffff000000000000000000000005.tlbin:system/app/mcRegistry/ffffffff000000000000000000000005.tlbin \
    vendor/samsung/hl3g/proprietary/app/mcRegistry/ffffffff000000000000000000000007.tlbin:system/app/mcRegistry/ffffffff000000000000000000000007.tlbin \
    vendor/samsung/hl3g/proprietary/app/mcRegistry/ffffffff000000000000000000000008.tlbin:system/app/mcRegistry/ffffffff000000000000000000000008.tlbin \
    vendor/samsung/hl3g/proprietary/app/mcRegistry/ffffffff000000000000000000000009.tlbin:system/app/mcRegistry/ffffffff000000000000000000000009.tlbin \
    vendor/samsung/hl3g/proprietary/app/mcRegistry/ffffffff00000000000000000000000a.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000a.tlbin \
    vendor/samsung/hl3g/proprietary/app/mcRegistry/ffffffff00000000000000000000000c.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000c.tlbin \
    vendor/samsung/hl3g/proprietary/app/mcRegistry/ffffffff00000000000000000000000d.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000d.tlbin \
    vendor/samsung/hl3g/proprietary/app/mcRegistry/ffffffff00000000000000000000000f.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000f.tlbin \
    vendor/samsung/hl3g/proprietary/app/mcRegistry/ffffffff000000000000000000000010.tlbin:system/app/mcRegistry/ffffffff000000000000000000000010.tlbin \
    vendor/samsung/hl3g/proprietary/app/mcRegistry/ffffffff000000000000000000000012.tlbin:system/app/mcRegistry/ffffffff000000000000000000000012.tlbin \
    vendor/samsung/hl3g/proprietary/app/mcRegistry/ffffffff000000000000000000000013.tlbin:system/app/mcRegistry/ffffffff000000000000000000000013.tlbin \
    vendor/samsung/hl3g/proprietary/app/mcRegistry/ffffffffd00000000000000000000004.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000004.tlbin \
    vendor/samsung/hl3g/proprietary/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin:system/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin \
    vendor/samsung/hl3g/proprietary/app/mcRegistry/fffffffff0000000000000000000001e.tlbin:system/app/mcRegistry/fffffffff0000000000000000000001e.tlbin \
    vendor/samsung/hl3g/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/samsung/hl3g/proprietary/lib/hw/audio.primary.universal5260.so:system/lib/hw/audio.primary.universal5260.so \
    vendor/samsung/hl3g/proprietary/lib/hw/camera.universal5260.so:system/lib/hw/camera.universal5260.so \
    vendor/samsung/hl3g/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/hl3g/proprietary/lib/hw/gralloc.exynos5.so:system/lib/hw/gralloc.exynos5.so \
    vendor/samsung/hl3g/proprietary/lib/hw/nfc_nci.universal5260.so:system/lib/hw/nfc_nci.universal5260.so \
    vendor/samsung/hl3g/proprietary/lib/hw/sensors.universal5260.so:system/lib/hw/sensors.universal5260.so \
    vendor/samsung/hl3g/proprietary/lib/hw/hwcomposer.exynos5.so:system/lib/hw/hwcomposer.exynos5.so \
    vendor/samsung/hl3g/proprietary/lib/hw/keystore.exynos5.so:system/lib/hw/keystore.exynos5.so \
    vendor/samsung/hl3g/proprietary/lib/hw/memtrack.exynos5.so:system/lib/hw/memtrack.exynos5.so \
    vendor/samsung/hl3g/proprietary/lib/hw/power.exynos5.so:system/lib/hw/power.exynos5.so \
    vendor/samsung/hl3g/proprietary/media/wireless_left.spi:system/media/wireless_left.spi \
    vendor/samsung/hl3g/proprietary/media/wireless_right.spi:system/media/wireless_right.spi \
    vendor/samsung/hl3g/proprietary/media/battery_cover.spi:system/media/battery_cover.spi \
    vendor/samsung/hl3g/proprietary/media/battery_error.spi:system/media/battery_error.spi \
    vendor/samsung/hl3g/proprietary/media/particle_intro.spi:system/media/particle_intro.spi \
    vendor/samsung/hl3g/proprietary/media/particle_loop.spi:system/media/particle_loop.spi \
    vendor/samsung/hl3g/proprietary/media/lcd_density.txt:system/media/lcd_density.txt \
    vendor/samsung/hl3g/proprietary/media/percentage.spi:system/media/percentage.spi \
    vendor/samsung/hl3g/proprietary/media/battery_temperature_error.spi:system/media/battery_temperature_error.spi \
    vendor/samsung/hl3g/proprietary/media/battery_low.spi:system/media/battery_low.spi \
    vendor/samsung/hl3g/proprietary/media/dock_error.spi:system/media/dock_error.spi \
    vendor/samsung/hl3g/proprietary/media/wave_loop.spi:system/media/wave_loop.spi \
    vendor/samsung/hl3g/proprietary/media/incompatible_charger.spi:system/media/incompatible_charger.spi \
    vendor/samsung/hl3g/proprietary/media/battery_temperature_limit.spi:system/media/battery_temperature_limit.spi \
    vendor/samsung/hl3g/proprietary/lib/omx/libOMX.Exynos.AVC.Decoder.so:system/lib/omx/libOMX.Exynos.AVC.Decoder.so \
    vendor/samsung/hl3g/proprietary/lib/omx/libOMX.Exynos.AVC.Encoder.so:system/lib/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/samsung/hl3g/proprietary/lib/omx/libOMX.Exynos.MPEG4.Decoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Decoder.so \
    vendor/samsung/hl3g/proprietary/lib/omx/libOMX.Exynos.MPEG4.Encoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Encoder.so \
    vendor/samsung/hl3g/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/samsung/hl3g/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
    vendor/samsung/hl3g/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
    vendor/samsung/hl3g/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/hl3g/proprietary/vendor/lib/libmalicore.bc:system/vendor/lib/libmalicore.bc \
    vendor/samsung/hl3g/proprietary/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
    vendor/samsung/hl3g/proprietary/vendor/lib/libRSDriverArm.so:system/vendor/lib/libRSDriverArm.so \
    vendor/samsung/hl3g/proprietary/vendor/firmware/bcm4335_V0105.0540.hcd:system/vendor/firmware/bcm4335_V0105.0540.hcd \
    vendor/samsung/hl3g/proprietary/lib/libwrappergps.so:system/lib/libwrappergps.so \
    vendor/samsung/hl3g/proprietary/lib/libvirtualdisplaymodule.so:system/lib/libvirtualdisplaymodule.so \
    vendor/samsung/hl3g/proprietary/lib/libvirtualdisplay.so:system/lib/libvirtualdisplay.so \
    vendor/samsung/hl3g/proprietary/lib/libsxqk_skia.so:system/lib/libsxqk_skia.so \
    vendor/samsung/hl3g/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/samsung/hl3g/proprietary/lib/libstagefright_hdcp.so:system/lib/libstagefright_hdcp.so \
    vendor/samsung/hl3g/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/hl3g/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/hl3g/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/hl3g/proprietary/lib/libsamsungSoundbooster.so:system/lib/libsamsungSoundbooster.so \
    vendor/samsung/hl3g/proprietary/lib/libsamsungRecord_zoom.so:system/lib/libsamsungRecord_zoom.so \
    vendor/samsung/hl3g/proprietary/lib/libsamsungRecord_ns.so:system/lib/libsamsungRecord_ns.so \
    vendor/samsung/hl3g/proprietary/lib/libsamsungRecord.so:system/lib/libsamsungRecord.so \
    vendor/samsung/hl3g/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/hl3g/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
    vendor/samsung/hl3g/proprietary/lib/libmpp.so:system/lib/libmpp.so \
    vendor/samsung/hl3g/proprietary/lib/libmplmpu.so:system/lib/libmplmpu.so \
    vendor/samsung/hl3g/proprietary/lib/libmllite.so:system/lib/libmllite.so \
    vendor/samsung/hl3g/proprietary/lib/libmaet.so:system/lib/libmaet.so \
    vendor/samsung/hl3g/proprietary/lib/libion_exynos.so:system/lib/libion_exynos.so \
    vendor/samsung/hl3g/proprietary/lib/libinvensense_hal.so:system/lib/libinvensense_hal.so \
    vendor/samsung/hl3g/proprietary/lib/libhwjpeg.so:system/lib/libhwjpeg.so \
    vendor/samsung/hl3g/proprietary/lib/libhwcutilsmodule.so:system/lib/libhwcutilsmodule.so \
    vendor/samsung/hl3g/proprietary/lib/libhwcutils.so:system/lib/libhwcutils.so \
    vendor/samsung/hl3g/proprietary/lib/libhdmimodule.so:system/lib/libhdmimodule.so \
    vendor/samsung/hl3g/proprietary/lib/libhdmi.so:system/lib/libhdmi.so \
    vendor/samsung/hl3g/proprietary/lib/libhdcp2.so:system/lib/libhdcp2.so \
    vendor/samsung/hl3g/proprietary/lib/libgdmcprov.so:system/lib/libgdmcprov.so \
    vendor/samsung/hl3g/proprietary/lib/libfimg.so:system/lib/libfimg.so \
    vendor/samsung/hl3g/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
    vendor/samsung/hl3g/proprietary/lib/libexynosv4l2.so:system/lib/libexynosv4l2.so \
    vendor/samsung/hl3g/proprietary/lib/libexynosutils.so:system/lib/libexynosutils.so \
    vendor/samsung/hl3g/proprietary/lib/libexynoscamera.so:system/lib/libexynoscamera.so \
    vendor/samsung/hl3g/proprietary/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
    vendor/samsung/hl3g/proprietary/lib/libdisplaymodule.so:system/lib/libdisplaymodule.so \
    vendor/samsung/hl3g/proprietary/lib/libdisplay.so:system/lib/libdisplay.so \
    vendor/samsung/hl3g/proprietary/lib/libcsc.so:system/lib/libcsc.so \
    vendor/samsung/hl3g/proprietary/lib/libaudio-ril.so:system/lib/libaudio-ril.so \
    vendor/samsung/hl3g/proprietary/lib/libatparser.so:system/lib/libatparser.so \
    vendor/samsung/hl3g/proprietary/lib/lib_Samsung_SB_AM_for_ICS_v04004.so:system/lib/lib_Samsung_SB_AM_for_ICS_v04004.so \
    vendor/samsung/hl3g/proprietary/lib/lib_Samsung_Resampler.so:system/lib/lib_Samsung_Resampler.so \
    vendor/samsung/hl3g/proprietary/lib/lib_DNSe_NRSS_ver226.so:system/lib/lib_DNSe_NRSS_ver226.so \
    vendor/samsung/hl3g/proprietary/lib/libMcRegistry.so:system/lib/libMcRegistry.so \
    vendor/samsung/hl3g/proprietary/lib/libMcClient.so:system/lib/libMcClient.so \
    vendor/samsung/hl3g/proprietary/lib/libExynosOMX_Resourcemanager.so:system/lib/libExynosOMX_Resourcemanager.so \
    vendor/samsung/hl3g/proprietary/lib/libExynosOMX_Core.so:system/lib/libExynosOMX_Core.so \
    vendor/samsung/hl3g/proprietary/lib/libExynosHWCService.so:system/lib/libExynosHWCService.so
